/** Informativa privacy — testo integrale dal sito attuale. */
export const privacyLines: string[] = [
  "Informativa Privacy",
  "Lo scopo del presente documento è di informare la persona fisica (di seguito “Interessato”) relativamente al trattamento dei suoi dati personali (di seguito “Dati Personali”) raccolti dal titolare del trattamento, KonnectAlps S.r.l., con sede legale in Via Praga, 5 TRENTO (38121), indirizzo e-mail info@konnectalps.it, (di seguito “Titolare”), tramite il sito web www.konnectAlps.it (di seguito “Applicazione”).",
  "Le modifiche e gli aggiornamenti saranno vincolanti non appena pubblicati sull’Applicazione. In caso di mancata accettazione delle modifiche apportate all’Informativa Privacy, l’Interessato è tenuto a cessare l’utilizzo di questa Applicazione e può richiedere al Titolare di cancellare i propri Dati Personali.",
  "Categorie di Dati Personali trattati",
  "Il Titolare tratta le seguenti tipologie di Dati Personali forniti volontariamente dall’Interessato:",
  "Dati di contatto: nome, cognome, indirizzo, e-mail, telefono, immagini, credenziali di autenticazione, eventuali ulteriori informazioni inviate dall’Interessato, etc.",
  "Dati fiscali e di pagamento: codice fiscale, partita IVA, dati della carta di credito, estremi del conto corrente bancario, etc.",
  "Il Titolare tratta le seguenti tipologie di Dati Personali raccolti in maniera automatizzata:",
  "Dati tecnici: Dati Personali prodotti dai dispositivi, dalle applicazioni, dagli strumenti e dai protocolli utilizzati, quali ad esempio, informazioni sul dispositivo utilizzato, indirizzi IP, tipo di browser, tipo di provider Internet (ISP). Tali Dati Personali possono lasciare tracce che, in particolare se combinate con identificativi univoci e altre informazioni ricevute dai server, possono essere utilizzate per creare profili delle persone fisiche",
  "Dati di navigazione e di utilizzo dell’Applicazione: quali, ad esempio, pagine visitate, numero di clic, azioni compiute, durata delle sessioni, etc.",
  "Il mancato conferimento da parte dell’Interessato dei Dati Personali per i quali sussiste l’obbligo legale, contrattuale o qualora costituiscano requisito necessario per la conclusione del contratto con il Titolare, comporterà l’impossibilità del Titolare di instaurare o proseguire il rapporto con l’Interessato.",
  "L’Interessato che comunichi al Titolare Dati Personali di terzi è direttamente ed esclusivamente responsabile della loro provenienza, raccolta, trattamento, comunicazione o diffusione.",
  "Cookie e tecnologie simili",
  "L’Applicazione usa cookie, web beacon, identificatori univoci e altre analoghe tecnologie per raccogliere Dati Personali dell’Interessato sulle pagine, sui collegamenti visitati e sulle altre azioni che si eseguono quando l’Interessato utilizza l’Applicazione. Essi vengono memorizzati per essere poi trasmessi alla successiva visita dell’Interessato. Si può prendere visione della Cookie Policy completa al seguente indirizzo: www.konnectalps.t/cookie-policy",
  "Base giuridica e finalità del trattamento",
  "Il trattamento dei Dati Personali è necessario:",
  "per l’esecuzione del contratto con l’Interessato e precisamente:",
  "adempimento di ogni obbligo derivante dal rapporto precontrattuale o contrattuale con l’Interessato",
  "La comunicazione dei Dati Personali ai fornitori di servizi di telecomunicazione è necessaria per consentire l’esecuzione del contratto e garantire la connettività e l’infrastruttura tecnica correlata ai servizi erogati dal Titolare",
  "registrazione e autenticazione dell’Interessato: per consentire all’Interessato di registrarsi sull’Applicazione, accedere e essere identificato anche tramite piattaforme esterne",
  "supporto e contatto con l’Interessato: per rispondere alle richieste dell’Interessato",
  "gestione dei pagamenti: per gestire i pagamenti tramite carta di credito, bonifico bancario o altri strumenti",
  "per obbligo di legge e precisamente:",
  "l’adempimento di qualunque obbligo previsto dalle vigenti normative, leggi e regolamenti, in particolare, in materia tributaria e fiscale",
  "sulla base del legittimo interesse del Titolare, per:",
  "finalità di marketing via email di prodotti e/o servizi del titolare per vendere direttamente i prodotti o servizi del Titolare utilizzando l’e-mail fornita dall’Interessato nel contesto della vendita di un prodotto o servizio analogo a quello oggetto della vendita",
  "gestione, ottimizzazione e monitoraggio dell’infrastruttura tecnica: per identificare e risolvere eventuali problemi tecnici, per migliorare le performance dell’Applicazione, per gestire e organizzare le informazioni in un sistema informatico (es. server, database, etc.)",
  "sicurezza e antifrode: per garantire la sicurezza del patrimonio, delle infrastrutture e delle reti del Titolare",
  "sulla base del consenso dell’Interessato, per:",
  "retargeting e remarketing: per raggiungere con un annuncio pubblicitario personalizzato l’Interessato che ha già visitato o ha dimostrato interesse per i prodotti e/o servizi offerti dall’Applicazione utilizzando i suoi Dati Personali. L’Interessato può effettuare l’opt-out visitando la pagina della Network Advertising Initiative",
  "finalità di marketing di prodotti e/o servizi del Titolare: per inviare informazioni o materiali commerciali e/o promozionali, per effettuare attività di vendita diretta di prodotti e/o servizi del Titolare o per compiere ricerche di mercato con modalità automatizzate e tradizionali",
  "finalità di marketing di prodotti e/o servizi di terzi: per inviare informazioni o materiali commerciali e/o promozionali di terzi, per effettuare attività di vendita diretta o per compiere ricerche di mercato dei loro prodotti e/o servizi con modalità automatizzate e tradizionali",
  "I Dati Personali dell’Interessato possono inoltre essere utilizzati dal Titolare per tutelarsi in giudizio avanti le sedi giudiziarie competenti.",
  "Modalità di trattamento e destinatari dei Dati Personali",
  "Il trattamento dei Dati Personali viene effettuato mediante strumenti cartacei e informatici con modalità organizzative e con logiche strettamente correlate alle finalità indicate e mediante l’adozione di adeguate misure di sicurezza.",
  "I Dati Personali sono trattati esclusivamente da:",
  "persone autorizzate dal Titolare del trattamento dei Dati Personali che si sono impegnate alla riservatezza o abbiano un adeguato obbligo legale di riservatezza;",
  "In particolare, i Dati Personali dell’Interessato potranno inoltre essere comunicati a fornitori di servizi di telecomunicazione, quali operatori di telefonia fissa, accessi internet e connettività mobile, i quali agiscono in qualità di titolari autonomi del trattamento. Tali soggetti sono tenuti a utilizzare le garanzie appropriate per proteggere i Dati Personali e possono accedere solo a quelli necessari per proprie finalità, connesse all’erogazione dei rispettivi servizi di comunicazione elettronica, nel rispetto della normativa vigente in materia di protezione dei dati personali;",
  "soggetti che operano in autonomia come distinti titolari del trattamento o da soggetti designati quali responsabili del trattamento dal Titolare al fine di svolgere tutte le attività di trattamento necessarie a perseguire le finalità di cui alla presente informativa (ad esempio, partner commerciali, consulenti, società informatiche, fornitori di servizi, hosting provider);",
  "soggetti o enti a cui è obbligatorio comunicare i Dati Personali per obbligo di legge o per ordine delle autorità.",
  "I soggetti sopra elencati sono tenuti a utilizzare le garanzie appropriate per proteggere i Dati Personali e possono accedere solo a quelli necessari per eseguire i compiti a loro assegnati.",
  "I Dati Personali non verranno diffusi indiscriminatamente in alcun modo.",
  "Luogo",
  "Se necessario, i Dati Personali potrebbero essere trasferiti a soggetti ubicati al di fuori del territorio dello Spazio Economico Europeo (SEE). Tutte le volte in cui i Dati Personali dovessero essere oggetto di trasferimento al di fuori del SEE, il Titolare adotterà ogni misura contrattuale idonea e necessaria a garantire un adeguato livello di protezione dei Dati Personali, inclusi – tra gli altri – gli accordi basati sulle clausole contrattuali standard per il trasferimento dei dati al di fuori del SEE, approvate dalla Commissione Europea. Per richiedere informazioni sulle specifiche garanzie adottate, l’Interessato può contattare il Titolare al seguente indirizzo e-mail info@konnectalps.it.",
  "Periodo di conservazione dei Dati Personali",
  "I Dati Personali saranno conservati per il periodo di tempo necessario ad adempiere alle finalità per i quali sono stati raccolti, in particolare:",
  "per finalità relative all’esecuzione del contratto tra il Titolare e l’Interessato, saranno conservati per tutta la durata del rapporto contrattuale e, dopo la cessazione, per il periodo di prescrizione ordinario pari a 10 anni. Nel caso di contenzioso giudiziale, per tutta la durata dello stesso, fino all’esaurimento dei termini di esperibilità delle azioni di impugnazione",
  "per finalità relative al legittimo interesse del Titolare, saranno conservati fino al compimento di tale interesse",
  "per l’adempimento di un obbligo di legge, per ordine di un’autorità e per la tutela in giudizio, saranno conservati nel rispetto delle tempistiche previste da detti obblighi, normative e comunque sino al compimento del termine prescrizionale previsto dalle norme in vigore",
  "per finalità basate sul consenso dell’Interessato, saranno conservati sino alla revoca del consenso",
  "Al termine del periodo di conservazione, tutti i Dati Personali saranno cancellati o conservati in una forma che non consenta l’identificazione dell’Interessato.",
  "Diritti dell’Interessato",
  "Gli Interessati possono esercitare determinati diritti con riferimento ai Dati Personali trattati dal Titolare. In particolare, l’Interessato ha il diritto di:",
  "essere informato sul trattamento dei propri Dati Personali",
  "revocare il consenso in ogni momento",
  "limitare il trattamento dei propri Dati Personali",
  "opporsi al trattamento dei propri Dati Personali",
  "accedere ai propri Dati Personali",
  "verificare e chiedere la rettifica dei propri Dati Personali",
  "ottenere la limitazione del trattamento dei propri Dati Personali",
  "ottenere la cancellazione dei propri Dati Personali",
  "trasferire i propri Dati Personali ad altro titolare",
  "proporre reclamo all’autorità di controllo della protezione dei propri Dati Personali e/o agire in sede giudiziale.",
  "Per esercitare i propri diritti, gli Interessati possono indirizzare una richiesta al seguente indirizzo e-mail info@konnectalps.it. Le richieste saranno prese in carico dal Titolare immediatamente ed evase nel più breve tempo possibile, in ogni caso entro 30 giorni.",
  "Ultimo aggiornamento: 01/01/2025"
]
